import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/ui/accessibility-fixtures')
  await page.waitForFunction(() => Boolean((document.querySelector('#__nuxt') as HTMLElement & { __vue_app__?: unknown })?.__vue_app__))
})

test('MultiSelect labels, errors, selection and chip keyboard removal', async ({ page }) => {
  const multi = page.getByRole('combobox', { name: 'Языки', exact: true })
  await expect(multi).toHaveAccessibleDescription('Проверьте выбор')
  await multi.focus()
  await multi.press('ArrowDown')
  const list = page.getByRole('listbox', { name: 'Языки' })
  await expect(list).toHaveAttribute('id', (await multi.getAttribute('aria-controls'))!)
  await expect(list.getByRole('option', { name: 'JavaScript' })).toBeFocused()
  await list.getByRole('option', { name: 'JavaScript' }).press('Enter')
  await expect(list.getByRole('option', { name: 'JavaScript' })).toHaveAttribute('aria-selected', 'false')
  await page.keyboard.press('Escape')
  await expect(multi).toBeFocused()
  await expect(multi).not.toHaveAttribute('aria-controls', /.+/)
  const remove = multi.getByRole('button', { name: 'Удалить Vue', exact: true })
  await remove.focus()
  await remove.press('Enter')
  await expect(multi.locator('.crs-chip')).toHaveCount(0)
  await expect(multi).toHaveAttribute('aria-expanded', 'false')
  await expect(multi).toBeFocused()
  await page.getByRole('button', { name: 'Снять ошибку' }).click()
  await expect(multi).not.toHaveAttribute('aria-describedby', /.+/)
  await expect(multi).toHaveAttribute('aria-invalid', 'false')
  await expect(page.getByRole('button', { name: 'Удалить Python' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Убрать курс' })).toBeVisible()
  const disabled = page.getByRole('combobox', { name: 'Недоступные языки' })
  await expect(disabled).toBeDisabled()
  await disabled.click({ force: true })
  await expect(disabled).toHaveAttribute('aria-expanded', 'false')
})

for (const width of [320, 1440]) {
  for (const kind of ['price', 'sort', 'mobile']) {
    test(`${kind} focus, keyboard and return at ${width}`, async ({ page }) => {
      await page.setViewportSize({ width, height: 900 })
      const trigger = page.getByRole('button', { name: kind === 'price' ? 'Открыть цену' : kind === 'sort' ? 'Открыть сортировку' : 'Открыть меню', exact: true })
      await trigger.click()
      const dialog = page.getByRole('dialog', { name: kind === 'price' ? 'Цена' : kind === 'sort' ? 'Сортировка' : 'Меню', exact: true })
      await expect(dialog).toBeVisible()
      await expect.poll(() => dialog.evaluate(el => el.contains(document.activeElement))).toBe(true)
      if (kind === 'sort') {
        await expect(dialog.getByRole('option', { name: 'Один' })).toBeFocused()
        await page.keyboard.press('ArrowDown')
        await expect(dialog.getByRole('option', { name: 'Два' })).toBeFocused()
        await page.keyboard.press('Enter')
        await expect(page.getByTestId('sort-value')).toHaveText('two')
        await expect(trigger).toBeFocused()
        await trigger.click()
      }
      for (let i = 0; i < 8; i++) {
        await page.keyboard.press(i % 2 ? 'Shift+Tab' : 'Tab')
        expect(await dialog.evaluate(el => el.contains(document.activeElement))).toBe(true)
      }
      await page.keyboard.press('Escape')
      await expect(dialog).toHaveCount(0)
      await expect(trigger).toBeFocused()
    })
  }
}

test('nested sheet Escape and focus restoration do not close parent', async ({ page }) => {
  await page.getByRole('button', { name: 'Открыть меню', exact: true }).click()
  const nested = page.getByRole('button', { name: 'Вложенная цена' })
  await nested.click()
  const price = page.getByRole('dialog', { name: 'Цена' })
  await price.getByRole('button', { name: 'Валюта' }).press('ArrowDown')
  await expect(price.getByRole('listbox')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(price.getByRole('listbox')).toHaveCount(0)
  await expect(price).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(price).toHaveCount(0)
  await expect(nested).toBeFocused()
  await expect(page.getByRole('dialog', { name: 'Меню' })).toBeVisible()
})

test('tabs skip disabled items, wrap, expose panels, and leave normal groups unchanged', async ({ page }) => {
  const first = page.getByRole('tab', { name: 'Первый' })
  const second = page.getByRole('tab', { name: 'Второй' })
  await first.focus()
  await first.press('ArrowRight')
  await expect(second).toBeFocused()
  await expect(second).toHaveAttribute('aria-selected', 'true')
  await expect(second).toHaveAttribute('aria-controls', 'panel-two')
  await expect(page.getByRole('tabpanel', { name: 'Второй' })).toBeVisible()
  await second.press('ArrowRight')
  await expect(first).toBeFocused()
  await first.press('End')
  await expect(second).toBeFocused()
  await second.press('Home')
  await expect(first).toBeFocused()
  await expect(second).toHaveAttribute('tabindex', '-1')
  const group = page.getByRole('group', { name: 'Обычная группа' })
  await expect(group.getByRole('button').first()).not.toHaveAttribute('tabindex')
  await expect(group.getByRole('button').first()).not.toHaveAttribute('aria-controls')
})

test('tooltip describes actual button, preserves existing description and dismisses with Escape', async ({ page }) => {
  const button = page.getByRole('button', { name: 'Кнопка с подсказкой' })
  await button.focus()
  await expect(button).toHaveAccessibleDescription('Существующее описание Подсказка кнопки')
  await expect(button.locator('..')).not.toHaveAttribute('tabindex', '0')
  await button.press('Escape')
  await expect(button).toBeFocused()
  await expect(button).toHaveAccessibleDescription('Существующее описание')
  const staticTrigger = page.locator('.crs-tooltip__trigger').last()
  await staticTrigger.focus()
  await expect(staticTrigger).toHaveAccessibleDescription('Подсказка текста')
  await staticTrigger.press('Escape')
  await expect(staticTrigger).not.toHaveAttribute('aria-describedby')
})

test('chart accessible name includes every value and fallback label', async ({ page }) => {
  await expect(page.getByRole('img', { name: 'График спроса. Январь: 0; Февраль: 12; Период 3: 5', exact: true })).toBeVisible()
})

test('initially open SSR price sheet receives focus after hydration', async ({ page }) => {
  await page.goto('/ui/preview?component=price-sheet')
  await page.waitForFunction(() => Boolean((document.querySelector('#__nuxt') as HTMLElement & { __vue_app__?: unknown })?.__vue_app__))
  await expect(page.getByRole('textbox', { name: 'Цена от' })).toBeFocused()
})

test('mouse actions retain price reset, currency selection, Done and menu group toggles', async ({ page }) => {
  const trigger = page.getByRole('button', { name: 'Открыть цену', exact: true })
  await trigger.click()
  const price = page.getByRole('dialog', { name: 'Цена' })
  await price.getByRole('textbox', { name: 'Цена от' }).fill('100')
  await price.getByRole('textbox', { name: 'Цена до' }).fill('500')
  await price.getByRole('button', { name: 'Валюта' }).click()
  await price.getByRole('option', { name: '€', exact: true }).click()
  await expect(price.getByRole('button', { name: 'Валюта' })).toHaveText('€')
  await price.getByRole('button', { name: 'Сбросить' }).click()
  await expect(price.getByRole('textbox', { name: 'Цена от' })).toHaveValue('')
  await expect(price.getByRole('textbox', { name: 'Цена до' })).toHaveValue('')
  await price.getByRole('button', { name: 'Готово' }).click()
  await expect(price).toHaveCount(0)
  await expect(trigger).toBeFocused()
  const menuTrigger = page.getByRole('button', { name: 'Открыть меню', exact: true })
  await menuTrigger.click()
  const group = page.locator('.crs-mobile-menu__group').first()
  await group.getByRole('button', { name: 'Свернуть', exact: true }).click()
  await expect(group.locator('nav')).toBeHidden()
  await group.getByRole('button', { name: 'Развернуть', exact: true }).click()
  await expect(group.locator('nav')).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть меню', exact: true }).click()
  await expect(menuTrigger).toBeFocused()
})

test('RTL tab direction follows the rendered direction', async ({ page }) => {
  const list = page.getByRole('tablist', { name: 'Пример табов' })
  await list.evaluate(element => element.setAttribute('dir', 'rtl'))
  const first = list.getByRole('tab', { name: 'Первый' })
  const second = list.getByRole('tab', { name: 'Второй' })
  await first.focus()
  await first.press('ArrowLeft')
  await expect(second).toBeFocused()
  await second.press('ArrowRight')
  await expect(first).toBeFocused()
})
