const root=document.documentElement;
const families=[
 ['navigation','Навигация',['Логотип слева','Компактная панель'],'Две шапки, выпадающее меню и мобильная навигация.'],
 ['header','Первый экран',['Текст + композиция','Центр + преимущества'],'Крупный Display, CTA и графический противовес.'],
 ['banner','Анонс',['Сообщение','Сообщение + ссылка'],'Закрываемая полоса перед основным контентом.'],
 ['content','Контент',['Карточки в ленте','Вертикальные вкладки','Текст + показатели','Композиция + темы'],'Четыре способа рассказать о продукте.'],
 ['feature','Преимущества',['Сетка 4 × 2','Строка показателей','Сетка 3 × 2'],'Один формат карточки в разных композициях.'],
 ['integration','Экосистема',['Карточки сервисов','Выбор сервиса'],'Вместо сторонних логотипов — готовые знаки Хабра.'],
 ['logo','Логотипы',['Общая панель','Отдельные плитки'],'Набор сервисов, без вымышленных партнёров.'],
 ['pricing','Тарифы',['Три варианта','Два варианта'],'Карточки и работающий выбор периода. Цены условные.'],
 ['team','Команда',['Горизонтальные карточки','Вертикальные карточки'],'Демонстрационные участники; инициалы вместо чужих фото.'],
 ['how-it-works','Этапы',['Последовательность'],'Вертикальная история: номер, задача и результат.'],
 ['blog','Материалы',['Три колонки','Две колонки'],'Превью, заголовок и автор; материал открывается в окне.'],
 ['testimonial','Отзывы',['Три цитаты','Четыре истории'],'Демонстрационные цитаты и подписи авторов.'],
 ['faq','Вопросы',['Две колонки','Одна колонка'],'Тематические фильтры и раскрывающиеся ответы.'],
 ['contact','Форма заявки',['Форма + контакты','Форма + место встречи'],'Крупные поля, согласие и локальная проверка формы.'],
 ['cta','Призыв к действию',['Центральный','Две карточки'],'Один основной сценарий или два направления.'],
 ['footer','Подвал',['Подписка справа','Подписка сверху'],'Навигация, логотип и форма подписки.']
];
const productNames={habr:'Хабр',career:'Карьера',courses:'Курсы'};
const services=['habr','career','courses','qna','business','promo'];
const serviceNames={...productNames,qna:'Q&A',business:'Бизнес',promo:'Промо'};
const titles=['Понятная задача','Экспертный взгляд','Практика вместе','Результат в проекте','Обратная связь','Новые знакомства','Полезные материалы','Поддержка команды'];
const descriptions=['Определите, что должно измениться для вашей аудитории.','Посмотрите на задачу глазами людей с реальным опытом.','Разберите приёмы на конкретных примерах и попробуйте сами.','Заберите решения, которые можно применить в своей работе.'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

// -------------------------------------------------------------------------
// Разметка стенда собирается из классов пакета: .button, .card, .form-field,
// .site-header, .hero, .program, .form-section, .footer-corp, .glass-chip,
// .product-lockup. Собственные .ml-* остались только там, где они отвечают
// за РАССТАНОВКУ демонстраций (.ml-grid, .ml-split, .ml-block, .ml-stage,
// .ml-scroll, .ml-section-head) или за элемент, которого в пакете нет
// (.ml-tag, .ml-avatar, .ml-price-card, .ml-faq-grid, .ml-map, .ml-glyph,
// .ml-demo-result, .ml-brand-art, .ml-textarea) — список ведётся в отчёте
// этапа и в шапке hds.css.
// -------------------------------------------------------------------------

// Знаки сервисов отдаются с общей точки монтирования сервера (tools/serve.mjs,
// /assets/logos/ → ../assets/logos). Тот же путь стоит в .product-lockup-mark
// пакета, поэтому картинка и компонент берут файл из одного места.
const logo=(p=root.dataset.product,word=false)=>`<img ${word?'class="ml-wordmark"':''} src="/assets/logos/${p}/${word?'wordmark-ru':'icon-detailed'}.svg" alt="${word?serviceNames[p]:''}" ${word?'':'aria-hidden="true"'}>`;
// Лок-ап пакета знает только три продукта (data-product на <html>); шесть
// сервисов витрины он не покрывает — там остаётся <img>.
const lockup=()=>`<a class="product-lockup" href="#header" aria-label="${productNames[root.dataset.product]}"><span class="product-lockup-mark" aria-hidden="true"></span><span class="product-lockup-word" aria-hidden="true"></span></a>`;
const brand=()=>`<a class="ml-logo" href="#header">${logo(root.dataset.product,true)}</a>`;
const btn=(text='Обсудить проект',outline=false,href='#contact')=>`<a class="button ${outline?'ml-btn-outline':''}" href="${href}">${text}</a>`;
const actions=(cls='ml-actions')=>`<div class="${cls}">${btn()}${btn('Посмотреть программу',true,'#content')}</div>`;
const heading=(text,lead='',center=false)=>`<div class="ml-section-head ${center?'ml-center':''}"><div><h2>${text}</h2>${lead?`<p>${lead}</p>`:''}</div></div>`;
const card=(i,extra='')=>`<article class="card ${extra}"><div class="ml-glyph" aria-hidden="true">${['↗','✳','◎','＋'][i%4]}</div><h3>${titles[i%8]}</h3><p>${descriptions[i%4]}</p></article>`;
const art=()=>`<div class="ml-brand-art" aria-label="Знак сервиса ${productNames[root.dataset.product]}"><div class="ml-brand-disc">${logo()}</div><span class="ml-art-label ml-art-label-top">Люди, которые создают</span><span class="ml-art-label ml-art-label-bottom">${productNames[root.dataset.product]} · сообщество</span><span class="ml-art-coordinate" aria-hidden="true">↗</span></div>`;
// Показатель — .card + .card-stat: снятый кегль числа 128 px. Подпись живёт
// вне карточки, иначе она унаследовала бы тот же кегль.
const stats=()=>`<div class="ml-stats">${[['3','дня для новых идей'],['12','тем из реальной практики'],['1','цель — следующий шаг']].map(([n,t])=>`<div class="ml-stat"><div class="card card-stat">${n}</div><span>${t}</span></div>`).join('')}</div>`;
const tabs=(items,attr='data-topic')=>`<div class="ml-tabs" role="group" aria-label="Выбор темы">${items.map((x,i)=>`<button type="button" ${attr}="${i}" aria-pressed="${i===0}">${x}</button>`).join('')}</div>`;
// Чип-плашка пакета — крупная: высота 121.972 px, кегль 44 px (снято с узлов).
// В стенде она едет в горизонтальном контейнере, чтобы измеренный размер
// показывался как есть и не растягивал страницу.
const chips=()=>`<div class="ml-scroll ml-chips">${['Продукт','Команда','Сообщество'].map(t=>`<span class="glass-chip"><span class="glass-chip-text">${t}</span></span>`).join('')}</div>`;
const field=(id,label,input)=>`<label class="form-field" for="${id}"><span class="form-field-hint">${label}</span>${input}</label>`;
const form=(id,short=false)=>`<form class="ml-fields" data-demo-form><div class="form-section-rows ${short?'':'form-section-rows-2'}">${!short?field(`${id}-name`,'Имя',`<input class="form-field-input" id="${id}-name" name="name" autocomplete="given-name" placeholder="Как к вам обращаться" required>`):''}${field(`${id}-email`,'Электронная почта',`<input class="form-field-input" id="${id}-email" name="email" type="email" autocomplete="email" placeholder="name@example.com" required>`)}</div>${!short?field(`${id}-message`,'О чём хотите поговорить',`<textarea class="form-field-input ml-textarea" id="${id}-message" name="message" placeholder="Несколько слов о вашей задаче" required></textarea>`):''}<label class="form-section-consent"><input class="form-field-box" type="checkbox" required><span class="form-section-note">Я согласен с условиями демонстрационной формы. Данные никуда не отправляются.</span></label><div class="form-section-actions"><button class="button" type="submit">${short?'Подписаться':'Отправить заявку'}</button></div><p class="ml-form-status" role="status"></p></form>`;
const footCols=()=>[['Проект',[['#content','О программе'],['#feature','Преимущества'],['#pricing','Участие']]],['Люди',[['#team','Команда'],['#testimonial','Отзывы'],['#contact','Контакты']]],['Полезное',[['#blog','Материалы'],['#faq','Вопросы'],['#how-it-works','Как всё устроено']]]].map(([h,links])=>`<div class="footer-corp-col"><h3 class="footer-corp-h">${h}</h3>${links.map(([href,t])=>`<a class="footer-corp-item" href="${href}">${t}</a>`).join('')}</div>`).join('');
const renderers={
 navigation:v=>`<header class="site-header" aria-label="Пример навигации ${v}"><div class="site-header-in">${lockup()}<nav class="ml-nav-links" aria-label="Разделы"><ul class="site-header-nav"><li><details><summary class="site-header-toggle">Направления</summary><div class="ml-dropdown"><a href="#content">Для продукта</a><a href="#team">Для команды</a><a href="#integration">Для сообщества</a></div></details></li><li><a class="site-header-link" href="#feature">Возможности</a></li>${v===1?'<li><a class="site-header-link" href="#blog">Материалы</a></li>':''}</ul></nav><div class="site-header-cta">${btn('Начать')}</div><details class="ml-mobile-menu"><summary class="site-header-toggle">Меню</summary><div class="ml-dropdown"><a href="#content">Программа</a><a href="#team">Команда</a><a href="#contact">Оставить заявку</a></div></details></div></header>`,
 header:v=>v===1?`<section class="hero hero-split"><div class="hero-in"><div><span class="ml-tag">${productNames[root.dataset.product]} · новые возможности</span><h2 class="hero-display">Люди.<br>Знания.<br>Практика.</h2><p class="hero-lead">Обмениваемся опытом, разбираем реальные задачи и находим людей, с которыми хочется делать больше.</p>${actions('hero-actions')}</div><div class="hero-art">${art()}</div></div></section><div class="ml-block"><div class="ml-divider"></div><div class="ml-logo-strip">${['habr','career','courses'].map(p=>logo(p,true)).join('')}</div></div>`:`<section class="hero"><div class="hero-in ml-center"><div class="ml-hero-center"><span class="ml-tag">Программа для тех, кто создаёт</span><h2 class="hero-display">Собираем идеи.<br>Меняем привычное.</h2><p class="hero-lead">Разбираемся в сложном, обмениваемся опытом и находим решения вместе.</p>${actions('hero-actions')}</div></div></section><div class="ml-block"><div class="ml-grid">${[0,1,2].map(i=>card(i)).join('')}</div></div>`,
 banner:v=>`<div class="ml-banner"><span aria-hidden="true">✳</span><span>${v===1?'Набор в новую программу открыт. Присоединяйтесь к следующему потоку.':'Новая встреча сообщества — уже в этом месяце.'}</span>${v===2?'<a href="#content">Узнать больше ↗</a>':''}<button class="ml-icon-btn" data-dismiss aria-label="Закрыть анонс">×</button></div><p class="ml-muted" hidden>Анонс закрыт. Смените вариант, чтобы показать его снова.</p>`,
 content:v=>{
   if(v===1)return `<div class="ml-block">${heading('Есть идея? Найдём ей применение.','Четыре направления — выберите то, с чего хотите начать.')}<div class="ml-scroll">${[0,1,2,3].map(i=>card(i)).join('')}</div><div class="ml-scroll-controls"><button class="ml-icon-btn" data-scroll="-1" aria-label="Предыдущие карточки">←</button><button class="ml-icon-btn" data-scroll="1" aria-label="Следующие карточки">→</button></div></div>`;
   if(v===2)return `<div class="ml-block">${heading('Выберите своё направление.')}<div class="ml-split"><div class="ml-tabs ml-vertical-tabs" role="group" aria-label="Направление">${['Продукт','Разработка','Команда','Сообщество'].map((t,i)=>`<button data-content="${i}" aria-pressed="${i===0}">${t}</button>`).join('')}</div><div class="ml-demo-result" data-content-result><strong>Продукт</strong><p>От идеи и исследования до понятного решения для аудитории.</p>${actions()}</div></div></div>`;
   return `<div class="ml-block"><div class="ml-split">${v===4?art():''}<div class="ml-stack"><span class="ml-tag">От опыта к действию</span><h2>${v===3?'Сильные решения рождаются вместе.':'Проверяем идеи на практике.'}</h2><p class="ml-lead">Профессиональное сообщество помогает взглянуть на задачу шире. Найдите людей, инструменты и знания для следующего шага.</p>${actions()}${v===4?chips():stats()}</div>${v===3?`<div class="ml-demo-result"><strong>Не просто слушать.<br>Попробовать.</strong><p>Задачи из реальных проектов, обсуждения и обратная связь.</p></div>`:''}</div></div>`;
 },
 feature:v=>v===2?`<div class="ml-block"><div class="ml-section-head"><h3>Меньше теории.<br>Больше полезного.</h3>${stats()}</div></div>`:v===3?`<div class="ml-block ml-center">${heading('Всё, чтобы сделать следующий шаг.','От первой идеи до результата, который можно показать команде.')}<div class="card-grid">${Array.from({length:6},(_,i)=>card(i)).join('')}</div></div>`:`<div class="ml-block">${heading('Всё, чтобы сделать следующий шаг.','От первой идеи до результата, который можно показать команде.')}<div class="ml-grid ml-grid-4">${Array.from({length:8},(_,i)=>card(i)).join('')}</div></div>`,
 integration:v=>`<div class="ml-block">${heading('Одна экосистема. Разные возможности.','Здесь используются наши готовые SVG-знаки сервисов.')} ${v===1?`<div class="ml-grid">${services.map(p=>`<article class="card"><div class="ml-glyph">${logo(p)}</div><h3>${serviceNames[p]}</h3><p>Люди, знания и возможности для профессионального роста.</p><button class="button ml-btn-outline" data-service="${p}">О сервисе</button></article>`).join('')}</div>`:`<div class="ml-split"><div class="ml-tabs" role="group" aria-label="Сервис">${services.map((p,i)=>`<button data-integration="${p}" aria-pressed="${i===0}">${serviceNames[p]}</button>`).join('')}</div><div class="card" data-integration-result><div class="ml-glyph">${logo('habr')}</div><h3>Хабр</h3><p>Делитесь опытом и находите полезное в профессиональном сообществе.</p>${btn('Обсудить возможности')}</div></div>`}</div>`,
 logo:v=>`<div class="ml-block">${heading('Сервисы, которые объединяют.')}<div class="${v===1?'card ml-service-logos':'ml-grid'}">${services.map(p=>v===1?`<div class="ml-service-logo">${logo(p,true)}</div>`:`<div class="card"><div class="ml-glyph">${logo(p)}</div><h3>${serviceNames[p]}</h3></div>`).join('')}</div></div>`,
 pricing:v=>`<div class="ml-block ${v===2?'ml-center':''}">${heading('Выберите формат участия.','Демонстрационные тарифы для проверки композиции.')}<div class="ml-billing" role="group" aria-label="Период оплаты"><button data-billing="month" aria-pressed="true">Месяц</button><button data-billing="year" aria-pressed="false">Год · −20%</button></div><div class="ml-grid ${v===2?'ml-grid-2':''}">${['Знакомство','Практика',...(v===1?['Для команды']:[])].map((t,i)=>`<article class="card ml-price-card ${i===1?'ml-featured':''}"><span class="ml-tag">${i===1?'Больше возможностей':i===0?'Первый шаг':'Совместная работа'}</span><h3>${t}</h3><div class="ml-price" data-price="${i}" aria-live="polite">${i===0?'0 ₽':i===1?'1 900 ₽':'По запросу'}${i===1?'<small> / мес.</small>':''}</div><p>${i===0?'Познакомиться с программой и сообществом.':i===1?'Углубиться в тему и применить знания.':'Подобрать формат под задачи команды.'}</p><ul class="ml-checks"><li>Доступ к материалам</li><li>Обсуждения с сообществом</li>${i>0?'<li>Практические разборы</li><li>Обратная связь</li>':''}</ul>${btn(i===2?'Обсудить задачу':'Выбрать формат',i!==1)}</article>`).join('')}</div></div>`,
 team:v=>`<div class="ml-block ${v===2?'ml-center':''}">${heading('Люди, с которыми хочется делать.','Имена и роли ниже — демонстрационные.')}<div class="ml-grid ${v===1?'ml-grid-2':'ml-grid-4'}">${['Анна Смирнова','Марк Волков','Ирина Соколова','Олег Морозов'].map((t,i)=>`<article class="card ${v===1?'ml-person':'ml-team-tall'}"><div class="ml-avatar" aria-hidden="true">${t.split(' ').map(s=>s[0]).join('')}</div><div><h3>${t}</h3><p>${['Продукт и исследования','Технологии','Сообщество','Образование'][i]}</p><a href="#contact">Связаться ↗</a></div></article>`).join('')}</div></div>`,
 'how-it-works':()=>`<section class="program"><div class="program-in"><div><span class="program-label">Как всё устроено</span><h2 class="program-title">От первого знакомства к результату.</h2></div><ol class="program-list">${['Расскажите о задаче','Выберите формат','Примените на практике'].map((t,i)=>`<li class="program-item"><div class="program-date">${i+1}<span class="program-date-cap">Этап</span></div><div><h3 class="program-item-title">${t}</h3><p class="program-item-text">${descriptions[i]}</p><div class="card"><h3>${['Контекст','План','Результат'][i]}</h3><p>${['Коротко опишите аудиторию, цель и ожидания.','Зафиксируйте ближайший шаг и критерии успеха.','Покажите решение, соберите обратную связь и улучшите его.'][i]}</p>${btn('Следующий шаг',true)}</div></div></li>`).join('')}</ol></div></section>`,
 blog:v=>`<div class="ml-block ${v===2?'ml-center':''}">${heading('Идеи, которыми стоит поделиться.','Материалы для тех, кто любит разбираться.')}<div class="ml-grid ${v===2?'ml-grid-2':''}">${['Как превратить наблюдение в идею','Почему сильной команде нужны вопросы','Что помогает доводить идеи до результата'].slice(0,v===2?2:3).map((t,i)=>`<article class="card"><div class="ml-article-art" aria-hidden="true">${['↗','Аа','✳'][i]}</div><button class="ml-article-link" data-article="${t}">${t}</button><p>Практические наблюдения, которые можно проверить в своём проекте.</p><div class="ml-article-meta">Редакция · 5 минут чтения</div></article>`).join('')}</div></div>`,
 testimonial:v=>`<div class="ml-block">${heading('Опыт, который остаётся с вами.','Демонстрационные отзывы — только для оценки дизайна.')}<div class="ml-grid ${v===2?'ml-grid-2':''}">${['Появился понятный следующий шаг, а не ещё один список идей.','Особенно ценны вопросы, которые сам себе раньше не задавал.','Получилось посмотреть на привычную задачу совсем по-другому.','Забрали несколько решений и уже проверяем их вместе с командой.'].slice(0,v===2?4:3).map((t,i)=>`<article class="card card-text"><div class="ml-quote-mark" aria-hidden="true">“</div><blockquote class="ml-quote">${t}</blockquote><div class="ml-divider"></div><p class="ml-quote-author">Участник программы ${i+1}<br><small>Пример отзыва</small></p></article>`).join('')}</div></div>`,
 faq:v=>`<div class="ml-block ${v===2?'ml-center':''}">${heading('Хорошие вопросы.<br>Понятные ответы.','Всё основное перед первым шагом.')} ${tabs(['Участие','Программа','Для команды'],'data-faq-filter')}<div class="ml-faq-grid ${v===2?'ml-single':''}">${[['Кому подойдёт программа?','Всем, кто хочет систематизировать опыт и найти новые подходы к рабочим задачам.'],['Нужен ли опыт?','Достаточно интереса к теме. Для практики можно взять задачу из своего проекта.'],['Как проходят встречи?','Короткие выступления чередуются с обсуждениями и самостоятельной работой.'],['Останутся ли материалы?','В этом демонстрационном сценарии материалы доступны участникам после встречи.'],['Можно прийти командой?','Да. Обсудите с организаторами общую цель и удобный формат участия.'],['Как задать свой вопрос?','Используйте форму заявки ниже — в прототипе она работает без отправки данных.']].map(([q,a],i)=>`<details data-faq-category="${Math.floor(i/2)}" ${i>=2?'hidden':''}><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></div>`,
 contact:v=>`<section class="form-section"><div class="form-section-in"><div class="form-section-head"><span class="form-section-label">Форма заявки</span><h2 class="form-section-title">Давайте начнём с разговора.</h2><p class="ml-lead">Расскажите о задаче — найдём подходящий формат.</p></div><div class="ml-split" style="align-items:start"><div class="card card-glass">${form('contact-'+v)}</div>${v===1?`<div class="ml-stack"><h3>Есть вопрос?</h3><p class="ml-lead">Опишите его в форме. Не нужно готовить подробное техническое задание — начнём с самого важного.</p><div class="card"><span class="ml-eyebrow">Первый шаг</span><h3>15 минут на знакомство</h3><p>Аудитория, задача и следующий шаг.</p></div></div>`:`<div class="ml-stack"><div class="ml-map" aria-label="Условное место встречи, не карта"><span>◎ Встретимся онлайн</span></div><p>Место и время встречи согласуем отдельно.</p></div>`}</div></div></section>`,
 cta:v=>v===1?`<div class="ml-block ml-center"><span class="ml-tag">Начинается с идеи</span><h2 class="ml-cta-title">Следующий шаг<br>можно сделать сегодня.</h2><p class="ml-lead ml-cta-lead">Расскажите, что хотите изменить. Остальное обсудим вместе.</p>${actions()}</div>`:`<div class="ml-block"><div class="ml-grid ml-grid-2"><div class="card"><div class="ml-glyph">↗</div><h3>Есть конкретная задача?</h3><p>Подберём формат под ваш проект и команду.</p>${btn('Обсудить проект')}</div><div class="card"><div class="ml-glyph">✳</div><h3>Хотите познакомиться?</h3><p>Посмотрите программу и выберите интересную тему.</p>${btn('Изучить программу',true,'#content')}</div></div></div>`,
 footer:v=>`<footer class="footer-corp">${v===2?`<div class="footer-corp-in ml-stack ml-footer-row"><div class="ml-split"><div class="ml-stack"><h2>Оставайтесь в теме.</h2><p class="ml-lead">Новости, идеи и приглашения на встречи.</p></div>${form('footer-top',true)}</div><div class="ml-divider"></div></div>`:`<div class="footer-corp-in ml-footer-row"><div class="ml-split" style="align-items:start"><div class="ml-stack">${brand()}<h3>Полезное в письме</h3><p class="ml-lead">Демонстрационная подписка.</p></div><div class="card">${form('footer-side',true)}</div></div></div>`}<div class="footer-corp-in footer-corp-cols ml-footer-row">${v===2?`<div class="footer-corp-col">${brand()}<p class="footer-corp-item">Локальный прототип пакета лендингов.</p></div>`:''}${footCols()}</div><div class="footer-corp-in footer-social-copyright ml-footer-bottom"><span class="footer-social-copyright-text">© HDS · Локальный прототип</span><a href="#top">Наверх ↑</a><span>Данные не отправляются</span></div></footer>`
};
document.querySelector('#contents').innerHTML=families.map(([id,name],i)=>`<a href="#${id}"><span>${String(i+1).padStart(2,'0')}</span>${name}</a>`).join('');
document.querySelector('#library').innerHTML=families.map(([id,name,variants,note],i)=>`<section class="ml-family" id="${id}"><div class="ml-family-head"><div><h2>${String(i+1).padStart(2,'0')} / ${name}</h2><p>${note}</p></div><div class="ml-family-tools"><label>Вариант<select data-variant="${id}" aria-label="Вариант: ${name}">${variants.map((v,n)=>`<option value="${n+1}">${String(n+1).padStart(2,'0')} · ${v}</option>`).join('')}</select></label></div></div><div class="ml-stage"></div></section>`).join('');
function renderFamily(id){const section=document.getElementById(id),v=Number(section.querySelector('select').value);section.querySelector('.ml-stage').innerHTML=renderers[id](v);}
families.forEach(([id])=>renderFamily(id));

// Образцы используют те же классы элементов и токены, что и секции ниже.
const typeRoles=['display','h1','h2','h3','lead','body','small','caption'];
document.querySelector('.ml-intro').insertAdjacentHTML('beforebegin',`<section id="elements" class="ml-family ml-foundations"><div class="ml-family-head"><div><h2>Элементы и типографика</h2><p>Текущая тема, продукт и характер. Значения обновляются при переключении и изменении ширины окна.</p><a href="primitives.html" target="_blank" rel="noopener">Сравнить с основной библиотекой</a></div></div><div class="ml-stage"><h3>Типографика</h3><div class="ml-type-list">${typeRoles.map((role,i)=>`<div class="ml-type-row"><div><strong>${role==='display'?'Display':role.toUpperCase()}</strong><small data-type-info="${role}"></small></div><p data-type-sample="${role}" style="font-family:var(--core-font-${i<4?'heading':'text'});font-size:var(--core-${role});line-height:var(--core-${role}-lh);letter-spacing:var(--core-${role}-ls,0);font-weight:${i===0?'var(--core-weight-display)':i<4?'600':'400'}">${i<4?'Люди и идеи':i===4?'Знания, которые помогают создавать новое.':'Делимся опытом, находим решения и делаем следующий шаг вместе.'}</p></div>`).join('')}</div><div class="ml-elements-grid"><section><h3>Кнопки и метки</h3><div class="ml-actions">${btn('Основная кнопка')}${btn('Вторичная',true)}<button class="button" disabled>Недоступна</button></div>${chips()}<p class="ml-spec-note">Наведите курсор или перейдите к элементам клавишей Tab, чтобы сравнить состояния.</p></section><section><h3>Поля формы</h3><div class="ml-fields">${field('sample-name','Имя','<input class="form-field-input" id="sample-name" placeholder="Как к вам обращаться">')}${field('sample-message','Сообщение','<textarea class="form-field-input ml-textarea" id="sample-message" placeholder="Расскажите о задаче"></textarea>')}<label class="form-section-consent"><input class="form-field-box" type="checkbox"><span class="form-section-note">Согласие с условиями</span></label></div></section></div><h3>Цвета</h3><div class="ml-swatches">${[['core-bg-page','Фон страницы'],['core-bg-surface','Поверхность'],['core-bg-field','Поле'],['core-border-field','Граница поля'],['core-text-primary','Основной текст'],['core-text-secondary','Вторичный текст'],['product-cta','Кнопка'],['product-accent','Акцент']].map(([token,label])=>`<div><div class="ml-swatch" style="background:var(--${token})" data-color-sample></div><strong>${label}</strong><small>${token}</small><small data-color-value></small></div>`).join('')}</div><h3>Скругления</h3><div class="ml-radius-samples">${[['0','0'],['6','6 px'],['16','16 px'],['pill','Пилюля']].map(([token,label])=>`<div><div style="border-radius:var(--core-radius-step-${token})"></div><small>${label}</small></div>`).join('')}</div></div></section>`);
document.querySelector('#contents').insertAdjacentHTML('afterbegin','<a href="#elements"><span>00</span>Элементы и типографика</a>');
function updateSpecValues(){
 document.querySelectorAll('[data-type-sample]').forEach(el=>{const s=getComputedStyle(el);document.querySelector(`[data-type-info="${el.dataset.typeSample}"]`).textContent=`${s.fontFamily.split(',')[0].replaceAll('"','')} · ${parseFloat(s.fontSize).toFixed(1).replace('.0','')} / ${parseFloat(s.lineHeight).toFixed(1).replace('.0','')} px · ${s.fontWeight}`;});
 document.querySelectorAll('[data-color-sample]').forEach(el=>{el.parentElement.querySelector('[data-color-value]').textContent=getComputedStyle(el).backgroundColor;});
}
updateSpecValues();
window.addEventListener('resize',updateSpecValues);
document.addEventListener('change',()=>requestAnimationFrame(updateSpecValues));
document.addEventListener('change',e=>{if(e.target.dataset.variant)renderFamily(e.target.dataset.variant);if(['product','theme','play'].includes(e.target.id)){root.dataset[e.target.id]=e.target.value;if(e.target.id==='product')families.forEach(([id])=>renderFamily(id));}});
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;const stage=b.closest('.ml-stage');
 if(b.hasAttribute('data-dismiss')){b.parentElement.hidden=true;b.parentElement.nextElementSibling.hidden=false;}
 if(b.dataset.scroll)stage.querySelector('.ml-scroll').scrollBy({left:Number(b.dataset.scroll)*320,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 if(b.dataset.billing){stage.querySelectorAll('[data-billing]').forEach(x=>x.setAttribute('aria-pressed',x===b));const p=stage.querySelector('[data-price="1"]');p.innerHTML=b.dataset.billing==='year'?'18 240 ₽<small> / год</small>':'1 900 ₽<small> / мес.</small>';}
 if(b.dataset.faqFilter!==undefined){stage.querySelectorAll('[data-faq-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));stage.querySelectorAll('[data-faq-category]').forEach(x=>x.hidden=x.dataset.faqCategory!==b.dataset.faqFilter);}
 if(b.dataset.content!==undefined){stage.querySelectorAll('[data-content]').forEach(x=>x.setAttribute('aria-pressed',x===b));const i=Number(b.dataset.content);stage.querySelector('[data-content-result]').innerHTML=`<strong>${['Продукт','Разработка','Команда','Сообщество'][i]}</strong><p>${descriptions[i]}</p>${actions()}`;}
 if(b.dataset.integration){stage.querySelectorAll('[data-integration]').forEach(x=>x.setAttribute('aria-pressed',x===b));const p=b.dataset.integration;stage.querySelector('[data-integration-result]').innerHTML=`<div class="ml-glyph">${logo(p)}</div><h3>${serviceNames[p]}</h3><p>Знания, опыт и профессиональные возможности в экосистеме Хабра.</p>${btn()}`;}
 if(b.dataset.article||b.dataset.service){document.querySelector('#article-title').textContent=b.dataset.article||serviceNames[b.dataset.service];document.querySelector('#article').showModal();}
 if(b.hasAttribute('data-close-dialog'))document.querySelector('#article').close();
});
document.addEventListener('submit',e=>{if(!e.target.matches('[data-demo-form]'))return;e.preventDefault();e.target.querySelector('.ml-form-status').textContent='Готово: форма заполнена корректно. Это прототип, данные не отправлены.';});
