const root=document.documentElement;
const families=[
 ['navigation','Навигация',['Логотип слева','Компактная панель'],'Две шапки, выпадающее меню и мобильная навигация.'],
 ['header','Первый экран',['Текст + композиция','Центр + преимущества'],'Крупный Display, CTA и графический противовес.'],
 ['banner','Анонс',['Сообщение','Сообщение + ссылка'],'Закрываемая полоса перед основным контентом.'],
 ['content','Контент',['Карточки в ленте','Вертикальные вкладки','Текст + показатели','Композиция + темы'],'Четыре способа рассказать о продукте.'],
 ['feature','Преимущества',['Сетка 4 × 2','Строка показателей','Сетка 3 × 2'],'Один формат карточки в разных композициях.'],
 ['integration','Экосистема',['Карточки сервисов','Выбор сервиса'],'Вместо сторонних логотипов — готовые знаки Хабра.'],
 ['logo','Логотипы',['Общая панель','Отдельные плитки'],'Набор сервисов, без вымышленных партнёров.'],
 ['pricing','Тарифы',['Три варианта','Два варианта'],'Карточки и работающий выбор периода. Цены условные.'],
 ['team','Команда',['Горизонтальные карточки','Вертикальные карточки'],'Демонстрационные участники; инициалы вместо чужих фото.'],
 ['how-it-works','Этапы',['Последовательность'],'Вертикальная история: номер, задача и результат.'],
 ['blog','Материалы',['Три колонки','Две колонки'],'Превью, заголовок и автор; материал открывается в окне.'],
 ['testimonial','Отзывы',['Три цитаты','Четыре истории'],'Демонстрационные цитаты и подписи авторов.'],
 ['faq','Вопросы',['Две колонки','Одна колонка'],'Тематические фильтры и раскрывающиеся ответы.'],
 ['contact','Форма заявки',['Форма + контакты','Форма + место встречи'],'Крупные поля, согласие и локальная проверка формы.'],
 ['cta','Призыв к действию',['Центральный','Две карточки'],'Один основной сценарий или два направления.'],
 ['footer','Подвал',['Подписка справа','Подписка сверху'],'Навигация, логотип и форма подписки.']
];
const productNames={habr:'Хабр',career:'Карьера',courses:'Курсы'};
const services=['habr','career','courses','qna','business','promo'];
const serviceNames={...productNames,qna:'Q&A',business:'Бизнес',promo:'Промо'};
const titles=['Понятная задача','Экспертный взгляд','Практика вместе','Результат в проекте','Обратная связь','Новые знакомства','Полезные материалы','Поддержка команды'];
const descriptions=['Определите, что должно измениться для вашей аудитории.','Посмотрите на задачу глазами людей с реальным опытом.','Разберите приёмы на конкретных примерах и попробуйте сами.','Заберите решения, которые можно применить в своей работе.'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logo=(p=root.dataset.product,word=false)=>`<img ${word?'class="ml-wordmark"':''} src="../../assets/logos/${p}/${word?'wordmark-ru':'icon-detailed'}.svg" alt="${word?serviceNames[p]:''}" ${word?'':'aria-hidden="true"'}>`;
const brand=()=>`<a class="ml-logo" href="#header">${logo(root.dataset.product,true)}</a>`;
const btn=(text='Обсудить проект',outline=false,href='#contact')=>`<a class="ml-btn ${outline?'ml-btn-outline':''}" href="${href}">${text}</a>`;
const actions=()=>`<div class="ml-actions">${btn()}${btn('Посмотреть программу',true,'#content')}</div>`;
const heading=(text,lead='',center=false)=>`<div class="ml-section-head ${center?'ml-center':''}"><div><h2>${text}</h2>${lead?`<p>${lead}</p>`:''}</div></div>`;
const card=(i,extra='')=>`<article class="ml-card ${extra}"><div class="ml-glyph" aria-hidden="true">${['↗','✳','◎','＋'][i%4]}</div><h3>${titles[i%8]}</h3><p>${descriptions[i%4]}</p></article>`;
const art=()=>`<div class="ml-brand-art" aria-label="Знак сервиса ${productNames[root.dataset.product]}"><div class="ml-brand-disc">${logo()}</div><span class="ml-art-label ml-art-label-top">Люди, которые создают</span><span class="ml-art-label ml-art-label-bottom">${productNames[root.dataset.product]} · сообщество</span><span class="ml-art-coordinate" aria-hidden="true">↗</span></div>`;
const stats=()=>`<div class="ml-stats"><div class="ml-stat"><strong>3 дня</strong><span>для новых идей</span></div><div class="ml-stat"><strong>12 тем</strong><span>из реальной практики</span></div><div class="ml-stat"><strong>1 цель</strong><span>сделать следующий шаг</span></div></div>`;
const tabs=(items,attr='data-topic')=>`<div class="ml-tabs" role="group" aria-label="Выбор темы">${items.map((x,i)=>`<button type="button" ${attr}="${i}" aria-pressed="${i===0}">${x}</button>`).join('')}</div>`;
const chips=()=>`<div class="ml-actions"><span class="ml-tag">Продукт</span><span class="ml-tag">Команда</span><span class="ml-tag">Сообщество</span></div>`;
const form=(id,short=false)=>`<form class="ml-form" data-demo-form><div class="${short?'ml-stack':'ml-grid ml-grid-2'}">${!short?`<label for="${id}-name">Имя<input id="${id}-name" name="name" autocomplete="given-name" placeholder="Как к вам обращаться" required></label>`:''}<label for="${id}-email">Электронная почта<input id="${id}-email" name="email" type="email" autocomplete="email" placeholder="name@example.com" required></label></div>${!short?`<label for="${id}-message">О чём хотите поговорить<textarea id="${id}-message" name="message" placeholder="Несколько слов о вашей задаче" required></textarea></label>`:''}<label class="ml-consent"><input type="checkbox" required><span>Я согласен с условиями демонстрационной формы. Данные никуда не отправляются.</span></label><button class="ml-btn" type="submit">${short?'Подписаться':'Отправить заявку'} </button><p class="ml-form-status" role="status"></p></form>`;
const footLinks=()=>`<div class="ml-footer-links"><div><strong>Проект</strong><a href="#content">О программе</a><a href="#feature">Преимущества</a><a href="#pricing">Участие</a></div><div><strong>Люди</strong><a href="#team">Команда</a><a href="#testimonial">Отзывы</a><a href="#contact">Контакты</a></div><div><strong>Полезное</strong><a href="#blog">Материалы</a><a href="#faq">Вопросы</a><a href="#how-it-works">Как всё устроено</a></div></div>`;
const renderers={
 navigation:v=>`<nav class="ml-nav" aria-label="Пример навигации ${v}">${brand()}<div class="ml-nav-links"><details><summary>Направления</summary><div class="ml-dropdown"><a href="#content">Для продукта</a><a href="#team">Для команды</a><a href="#integration">Для сообщества</a></div></details><a href="#feature">Возможности</a>${v===1?'<a href="#blog">Материалы</a>':''}</div><div class="ml-actions" style="margin:0">${btn('Начать')}</div><details class="ml-mobile-menu"><summary>Меню</summary><div class="ml-dropdown"><a href="#content">Программа</a><a href="#team">Команда</a><a href="#contact">Оставить заявку</a></div></details></nav>`,
 header:v=>v===1?`<div class="ml-block"><div class="ml-split"><div><span class="ml-tag">${productNames[root.dataset.product]} · новые возможности</span><h2 class="ml-display"><span>Люди.</span><span>Знания.</span><span>Практика.</span></h2><p class="ml-lead">Обмениваемся опытом, разбираем реальные задачи и находим людей, с которыми хочется делать больше.</p>${actions()}</div>${art()}</div><div class="ml-divider"></div><div class="ml-logo-strip">${['habr','career','courses'].map(p=>logo(p,true)).join('')}</div></div>`:`<div class="ml-block ml-center"><div class="ml-hero-center"><span class="ml-tag">Программа для тех, кто создаёт</span><h2 class="ml-display">Собираем идеи.<br>Меняем привычное.</h2><p class="ml-lead">Разбираемся в сложном, обмениваемся опытом и находим решения вместе.</p>${actions()}</div><div class="ml-grid">${[0,1,2].map(i=>card(i)).join('')}</div></div>`,
 banner:v=>`<div class="ml-banner"><span aria-hidden="true">✳</span><span>${v===1?'Набор в новую программу открыт. Присоединяйтесь к следующему потоку.':'Новая встреча сообщества — уже в этом месяце.'}</span>${v===2?'<a href="#content">Узнать больше ↗</a>':''}<button class="ml-icon-btn" data-dismiss aria-label="Закрыть анонс">×</button></div><p class="ml-muted" hidden>Анонс закрыт. Смените вариант, чтобы показать его снова.</p>`,
 content:v=>{
   if(v===1)return `<div class="ml-block">${heading('Есть идея? Найдём ей применение.','Четыре направления — выберите то, с чего хотите начать.')}<div class="ml-scroll">${[0,1,2,3].map(i=>card(i)).join('')}</div><div class="ml-scroll-controls"><button class="ml-icon-btn" data-scroll="-1" aria-label="Предыдущие карточки">←</button><button class="ml-icon-btn" data-scroll="1" aria-label="Следующие карточки">→</button></div></div>`;
   if(v===2)return `<div class="ml-block">${heading('Выберите своё направление.')}<div class="ml-split"><div class="ml-tabs ml-vertical-tabs" role="group" aria-label="Направление">${['Продукт','Разработка','Команда','Сообщество'].map((t,i)=>`<button data-content="${i}" aria-pressed="${i===0}">${t}</button>`).join('')}</div><div class="ml-demo-result" data-content-result><strong>Продукт</strong><p>От идеи и исследования до понятного решения для аудитории.</p>${actions()}</div></div></div>`;
   return `<div class="ml-block"><div class="ml-split">${v===4?art():''}<div class="ml-stack"><span class="ml-tag">От опыта к действию</span><h2>${v===3?'Сильные решения рождаются вместе.':'Проверяем идеи на практике.'}</h2><p class="ml-lead">Профессиональное сообщество помогает взглянуть на задачу шире. Найдите людей, инструменты и знания для следующего шага.</p>${actions()}${v===4?chips():stats()}</div>${v===3?`<div class="ml-demo-result"><strong>Не просто слушать.<br>Попробовать.</strong><p>Задачи из реальных проектов, обсуждения и обратная связь.</p></div>`:''}</div></div>`;
 },
 feature:v=>v===2?`<div class="ml-block"><div class="ml-section-head"><h3>Меньше теории.<br>Больше полезного.</h3>${stats()}</div></div>`:`<div class="ml-block ${v===3?'ml-center':''}">${heading('Всё, чтобы сделать следующий шаг.','От первой идеи до результата, который можно показать команде.')}<div class="ml-grid ${v===1?'ml-grid-4':''}">${Array.from({length:v===1?8:6},(_,i)=>card(i)).join('')}</div></div>`,
 integration:v=>`<div class="ml-block">${heading('Одна экосистема. Разные возможности.','Здесь используются наши готовые SVG-знаки сервисов.')} ${v===1?`<div class="ml-grid">${services.map(p=>`<article class="ml-card"><div class="ml-glyph">${logo(p)}</div><h3>${serviceNames[p]}</h3><p>Люди, знания и возможности для профессионального роста.</p><button class="ml-btn ml-btn-outline" data-service="${p}">О сервисе</button></article>`).join('')}</div>`:`<div class="ml-split"><div class="ml-tabs" role="group" aria-label="Сервис">${services.map((p,i)=>`<button data-integration="${p}" aria-pressed="${i===0}">${serviceNames[p]}</button>`).join('')}</div><div class="ml-card" data-integration-result><div class="ml-glyph">${logo('habr')}</div><h3>Хабр</h3><p>Делитесь опытом и находите полезное в профессиональном сообществе.</p>${btn('Обсудить возможности')}</div></div>`}</div>`,
 logo:v=>`<div class="ml-block">${heading('Сервисы, которые объединяют.')}<div class="${v===1?'ml-card ml-service-logos':'ml-grid ml-grid-3'}">${services.map(p=>v===1?`<div class="ml-service-logo">${logo(p,true)}</div>`:`<div class="ml-card"><div class="ml-glyph">${logo(p)}</div><h3>${serviceNames[p]}</h3></div>`).join('')}</div></div>`,
 pricing:v=>`<div class="ml-block ${v===2?'ml-center':''}">${heading('Выберите формат участия.','Демонстрационные тарифы для проверки композиции.')}<div class="ml-billing" role="group" aria-label="Период оплаты"><button data-billing="month" aria-pressed="true">Месяц</button><button data-billing="year" aria-pressed="false">Год · −20%</button></div><div class="ml-grid ${v===2?'ml-grid-2':''}">${['Знакомство','Практика',...(v===1?['Для команды']:[])].map((t,i)=>`<article class="ml-card ml-price-card ${i===1?'ml-featured':''}"><span class="ml-tag">${i===1?'Больше возможностей':i===0?'Первый шаг':'Совместная работа'}</span><h3>${t}</h3><div class="ml-price" data-price="${i}" aria-live="polite">${i===0?'0 ₽':i===1?'1 900 ₽':'По запросу'}${i===1?'<small> / мес.</small>':''}</div><p>${i===0?'Познакомиться с программой и сообществом.':i===1?'Углубиться в тему и применить знания.':'Подобрать формат под задачи команды.'}</p><ul class="ml-checks"><li>Доступ к материалам</li><li>Обсуждения с сообществом</li>${i>0?'<li>Практические разборы</li><li>Обратная связь</li>':''}</ul>${btn(i===2?'Обсудить задачу':'Выбрать формат',i!==1)}</article>`).join('')}</div></div>`,
 team:v=>`<div class="ml-block ${v===2?'ml-center':''}">${heading('Люди, с которыми хочется делать.','Имена и роли ниже — демонстрационные.')}<div class="ml-grid ${v===1?'ml-grid-2':'ml-grid-4'}">${['Анна Смирнова','Марк Волков','Ирина Соколова','Олег Морозов'].map((t,i)=>`<article class="ml-card ${v===1?'ml-person':'ml-team-tall'}"><div class="ml-avatar" aria-hidden="true">${t.split(' ').map(s=>s[0]).join('')}</div><div><h3>${t}</h3><p>${['Продукт и исследования','Технологии','Сообщество','Образование'][i]}</p><a href="#contact">Связаться ↗</a></div></article>`).join('')}</div></div>`,
 'how-it-works':()=>`<div class="ml-block">${heading('От первого знакомства к результату.','Три этапа, чтобы двигаться последовательно.')} ${['Расскажите о задаче','Выберите формат','Примените на практике'].map((t,i)=>`<div class="ml-step"><span class="ml-step-num">${i+1}</span><div class="ml-stack"><h3>${t}</h3><p class="ml-lead">${descriptions[i]}</p></div><div class="ml-card"><h3>${['Контекст','План','Результат'][i]}</h3><p>${['Коротко опишите аудиторию, цель и ожидания.','Зафиксируйте ближайший шаг и критерии успеха.','Покажите решение, соберите обратную связь и улучшите его.'][i]}</p>${btn('Следующий шаг',true)}</div></div>`).join('')}</div>`,
 blog:v=>`<div class="ml-block ${v===2?'ml-center':''}">${heading('Идеи, которыми стоит поделиться.','Материалы для тех, кто любит разбираться.')}<div class="ml-grid ${v===2?'ml-grid-2':''}">${['Как превратить наблюдение в идею','Почему сильной команде нужны вопросы','Что помогает доводить идеи до результата'].slice(0,v===2?2:3).map((t,i)=>`<article class="ml-card"><div class="ml-article-art" aria-hidden="true">${['↗','Аа','✳'][i]}</div><button class="ml-article-link" data-article="${t}">${t}</button><p>Практические наблюдения, которые можно проверить в своём проекте.</p><div class="ml-article-meta">Редакция · 5 минут чтения</div></article>`).join('')}</div></div>`,
 testimonial:v=>`<div class="ml-block">${heading('Опыт, который остаётся с вами.','Демонстрационные отзывы — только для оценки дизайна.')}<div class="ml-grid ${v===2?'ml-grid-2':''}">${['Появился понятный следующий шаг, а не ещё один список идей.','Особенно ценны вопросы, которые сам себе раньше не задавал.','Получилось посмотреть на привычную задачу совсем по-другому.','Забрали несколько решений и уже проверяем их вместе с командой.'].slice(0,v===2?4:3).map((t,i)=>`<article class="ml-card"><div class="ml-quote-mark" aria-hidden="true">“</div><blockquote class="ml-quote">${t}</blockquote><div class="ml-divider"></div><p>Участник программы ${i+1}<br><small>Пример отзыва</small></p></article>`).join('')}</div></div>`,
 faq:v=>`<div class="ml-block ${v===2?'ml-center':''}">${heading('Хорошие вопросы.<br>Понятные ответы.','Всё основное перед первым шагом.')} ${tabs(['Участие','Программа','Для команды'],'data-faq-filter')}<div class="ml-faq-grid ${v===2?'ml-single':''}">${[['Кому подойдёт программа?','Всем, кто хочет систематизировать опыт и найти новые подходы к рабочим задачам.'],['Нужен ли опыт?','Достаточно интереса к теме. Для практики можно взять задачу из своего проекта.'],['Как проходят встречи?','Короткие выступления чередуются с обсуждениями и самостоятельной работой.'],['Останутся ли материалы?','В этом демонстрационном сценарии материалы доступны участникам после встречи.'],['Можно прийти командой?','Да. Обсудите с организаторами общую цель и удобный формат участия.'],['Как задать свой вопрос?','Используйте форму заявки ниже — в прототипе она работает без отправки данных.']].map(([q,a],i)=>`<details data-faq-category="${Math.floor(i/2)}" ${i>=2?'hidden':''}><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></div>`,
 contact:v=>`<div class="ml-block">${heading('Давайте начнём с разговора.','Расскажите о задаче — найдём подходящий формат.')}<div class="ml-split" style="align-items:start"><div class="ml-card">${form('contact-'+v)}</div>${v===1?`<div class="ml-stack"><h3>Есть вопрос?</h3><p class="ml-lead">Опишите его в форме. Не нужно готовить подробное техническое задание — начнём с самого важного.</p><div class="ml-card"><span class="ml-eyebrow">Первый шаг</span><h3>15 минут на знакомство</h3><p>Аудитория, задача и следующий шаг.</p></div></div>`:`<div class="ml-stack"><div class="ml-map" aria-label="Условное место встречи, не карта"><span>◎ Встретимся онлайн</span></div><p>Место и время встречи согласуем отдельно.</p></div>`}</div></div>`,
 cta:v=>v===1?`<div class="ml-block ml-center"><span class="ml-tag">Начинается с идеи</span><h2 style="max-width:800px;margin:24px auto;font-size:var(--core-h1);line-height:var(--core-h1-lh)">Следующий шаг<br>можно сделать сегодня.</h2><p class="ml-lead" style="margin-inline:auto">Расскажите, что хотите изменить. Остальное обсудим вместе.</p>${actions()}</div>`:`<div class="ml-block"><div class="ml-grid ml-grid-2"><div class="ml-card"><div class="ml-glyph">↗</div><h3>Есть конкретная задача?</h3><p>Подберём формат под ваш проект и команду.</p>${btn('Обсудить проект')}</div><div class="ml-card"><div class="ml-glyph">✳</div><h3>Хотите познакомиться?</h3><p>Посмотрите программу и выберите интересную тему.</p>${btn('Изучить программу',true,'#content')}</div></div></div>`,
 footer:v=>`<footer class="ml-block">${v===2?`<div class="ml-split"><div class="ml-stack"><h2>Оставайтесь в теме.</h2><p class="ml-lead">Новости, идеи и приглашения на встречи.</p></div>${form('footer-top',true)}</div><div class="ml-divider"></div>`:''}<div class="ml-split" style="align-items:start"><div class="ml-stack">${brand()}${footLinks()}</div>${v===1?`<div class="ml-card"><h3>Полезное в письме</h3><p>Демонстрационная подписка.</p>${form('footer-side',true)}</div>`:`<div class="ml-demo-result"><strong>До встречи.</strong><p>Хорошие идеи любят компанию.</p>${btn('Связаться',true)}</div>`}</div><div class="ml-footer-bottom"><span>© HDS · Локальный прототип</span><a href="#top">Наверх ↑</a><span>Данные не отправляются</span></div></footer>`
};
document.querySelector('#contents').innerHTML=families.map(([id,name],i)=>`<a href="#${id}"><span>${String(i+1).padStart(2,'0')}</span>${name}</a>`).join('');
document.querySelector('#library').innerHTML=families.map(([id,name,variants,note],i)=>`<section class="ml-family" id="${id}"><div class="ml-family-head"><div><h2>${String(i+1).padStart(2,'0')} / ${name}</h2><p>${note}</p></div><div class="ml-family-tools"><label>Вариант<select data-variant="${id}" aria-label="Вариант: ${name}">${variants.map((v,n)=>`<option value="${n+1}">${String(n+1).padStart(2,'0')} · ${v}</option>`).join('')}</select></label></div></div><div class="ml-stage"></div></section>`).join('');
function renderFamily(id){const section=document.getElementById(id),v=Number(section.querySelector('select').value);section.querySelector('.ml-stage').innerHTML=renderers[id](v);}
families.forEach(([id])=>renderFamily(id));

// Образцы используют те же классы элементов и токены, что и секции ниже.
const typeRoles=['display','h1','h2','h3','lead','body','small','caption'];
document.querySelector('.ml-intro').insertAdjacentHTML('beforebegin',`<section id="elements" class="ml-family ml-foundations"><div class="ml-family-head"><div><h2>Элементы и типографика</h2><p>Текущая тема, продукт и характер. Значения обновляются при переключении и изменении ширины окна.</p><a href="../../landings/showcase/primitives.html" target="_blank" rel="noopener">Сравнить с основной библиотекой</a></div></div><div class="ml-stage"><h3>Типографика</h3><div class="ml-type-list">${typeRoles.map((role,i)=>`<div class="ml-type-row"><div><strong>${role==='display'?'Display':role.toUpperCase()}</strong><small data-type-info="${role}"></small></div><p data-type-sample="${role}" style="font-family:var(--core-font-${i<4?'heading':'text'});font-size:var(--core-${role});line-height:var(--core-${role}-lh);letter-spacing:var(--core-${role}-ls,0);font-weight:${i===0?'var(--core-weight-display)':i<4?'600':'400'}">${i<4?'Люди и идеи':i===4?'Знания, которые помогают создавать новое.':'Делимся опытом, находим решения и делаем следующий шаг вместе.'}</p></div>`).join('')}</div><div class="ml-elements-grid"><section><h3>Кнопки и метки</h3><div class="ml-actions">${btn('Основная кнопка')}${btn('Вторичная',true)}<button class="ml-btn" disabled>Недоступна</button></div>${chips()}<p class="ml-spec-note">Наведите курсор или перейдите к элементам клавишей Tab, чтобы сравнить состояния.</p></section><section><h3>Поля формы</h3><div class="ml-form"><label for="sample-name">Имя<input id="sample-name" placeholder="Как к вам обращаться"></label><label for="sample-message">Сообщение<textarea id="sample-message" placeholder="Расскажите о задаче"></textarea></label><label class="ml-consent"><input type="checkbox"><span>Согласие с условиями</span></label></div></section></div><h3>Цвета</h3><div class="ml-swatches">${[['core-bg-page','Фон страницы'],['core-bg-surface','Поверхность'],['core-bg-field','Поле'],['core-border-field','Граница поля'],['core-text-primary','Основной текст'],['core-text-secondary','Вторичный текст'],['product-cta','Кнопка'],['product-accent','Акцент']].map(([token,label])=>`<div><div class="ml-swatch" style="background:var(--${token})" data-color-sample></div><strong>${label}</strong><small>${token}</small><small data-color-value></small></div>`).join('')}</div><h3>Скругления</h3><div class="ml-radius-samples">${[['0','0'],['6','6 px'],['16','16 px'],['pill','Пилюля']].map(([token,label])=>`<div><div style="border-radius:var(--core-radius-step-${token})"></div><small>${label}</small></div>`).join('')}</div></div></section>`);
document.querySelector('#contents').insertAdjacentHTML('afterbegin','<a href="#elements"><span>00</span>Элементы и типографика</a>');
function updateSpecValues(){
 document.querySelectorAll('[data-type-sample]').forEach(el=>{const s=getComputedStyle(el);document.querySelector(`[data-type-info="${el.dataset.typeSample}"]`).textContent=`${s.fontFamily.split(',')[0].replaceAll('"','')} · ${parseFloat(s.fontSize).toFixed(1).replace('.0','')} / ${parseFloat(s.lineHeight).toFixed(1).replace('.0','')} px · ${s.fontWeight}`;});
 document.querySelectorAll('[data-color-sample]').forEach(el=>{el.parentElement.querySelector('[data-color-value]').textContent=getComputedStyle(el).backgroundColor;});
}
updateSpecValues();
window.addEventListener('resize',updateSpecValues);
document.addEventListener('change',()=>requestAnimationFrame(updateSpecValues));
document.addEventListener('change',e=>{if(e.target.dataset.variant)renderFamily(e.target.dataset.variant);if(['product','theme','play'].includes(e.target.id)){root.dataset[e.target.id]=e.target.value;if(e.target.id==='product')families.forEach(([id])=>renderFamily(id));}});
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;const stage=b.closest('.ml-stage');
 if(b.hasAttribute('data-dismiss')){b.parentElement.hidden=true;b.parentElement.nextElementSibling.hidden=false;}
 if(b.dataset.scroll)stage.querySelector('.ml-scroll').scrollBy({left:Number(b.dataset.scroll)*320,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 if(b.dataset.billing){stage.querySelectorAll('[data-billing]').forEach(x=>x.setAttribute('aria-pressed',x===b));const p=stage.querySelector('[data-price="1"]');p.innerHTML=b.dataset.billing==='year'?'18 240 ₽<small> / год</small>':'1 900 ₽<small> / мес.</small>';}
 if(b.dataset.faqFilter!==undefined){stage.querySelectorAll('[data-faq-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));stage.querySelectorAll('[data-faq-category]').forEach(x=>x.hidden=x.dataset.faqCategory!==b.dataset.faqFilter);}
 if(b.dataset.content!==undefined){stage.querySelectorAll('[data-content]').forEach(x=>x.setAttribute('aria-pressed',x===b));const i=Number(b.dataset.content);stage.querySelector('[data-content-result]').innerHTML=`<strong>${['Продукт','Разработка','Команда','Сообщество'][i]}</strong><p>${descriptions[i]}</p>${actions()}`;}
 if(b.dataset.integration){stage.querySelectorAll('[data-integration]').forEach(x=>x.setAttribute('aria-pressed',x===b));const p=b.dataset.integration;stage.querySelector('[data-integration-result]').innerHTML=`<div class="ml-glyph">${logo(p)}</div><h3>${serviceNames[p]}</h3><p>Знания, опыт и профессиональные возможности в экосистеме Хабра.</p>${btn()}`;}
 if(b.dataset.article||b.dataset.service){document.querySelector('#article-title').textContent=b.dataset.article||serviceNames[b.dataset.service];document.querySelector('#article').showModal();}
 if(b.hasAttribute('data-close-dialog'))document.querySelector('#article').close();
});
document.addEventListener('submit',e=>{if(!e.target.matches('[data-demo-form]'))return;e.preventDefault();e.target.querySelector('.ml-form-status').textContent='Готово: форма заполнена корректно. Это прототип, данные не отправлены.';});
