<script setup lang="ts">
const open=defineModel<boolean>({default:false})
withDefaults(defineProps<{title?:string}>(),{title:'Меню'})
const groups=ref([
  {title:'Все курсы',open:true,items:['Популярные курсы','Программирование и IT','Аналитика и Data Science','Дизайн и контент','Маркетинг и продажи','Финансы и бухгалтерия','Посмотреть все']},
  {title:'Школы и Вузы',open:true,items:['Все школы и вузы','Рейтинг школ и вузов','Отзывы о курсах и программах','Промокоды и акции 2026']}
])
const services=[{label:'Хабр',service:'habr' as const},{label:'Q&A',service:'qna' as const},{label:'Карьера',service:'career' as const},{label:'Курсы',service:'courses' as const}]
function onKeydown(event:KeyboardEvent){if(event.key==='Escape')open.value=false}
onMounted(()=>window.addEventListener('keydown',onKeydown));onBeforeUnmount(()=>window.removeEventListener('keydown',onKeydown))
</script>
<template><Teleport to="body"><Transition name="crs-menu"><aside v-if="open" class="crs-mobile-menu" role="dialog" aria-modal="true" :aria-label="title"><header><p>{{title}}</p><IconButton label="Закрыть меню" icon="i-tabler-x" variant="ghost" size="s" :icon-size="24" hover="none" @click="open=false"/></header><section v-for="group in groups" :key="group.title" class="crs-mobile-menu__group"><div><h2>{{group.title}}</h2><IconButton class="crs-mobile-menu__toggle" :label="group.open?'Свернуть':'Развернуть'" icon="i-tabler-chevron-down" variant="ghost" size="s" :icon-size="24" hover="none" :rotated="group.open" :aria-expanded="group.open" @click="group.open=!group.open"/></div><nav v-show="group.open"><Link v-for="item in group.items" :key="item" href="#" tone="inherit" layout="flex" :class="['crs-mobile-menu__link',{'crs-mobile-menu__more':item==='Посмотреть все'}]">{{item}}</Link></nav></section><section class="crs-mobile-menu__group"><div><h2>Все сервисы Хабра</h2></div><nav><Link v-for="item in services" :key="item.label" class="crs-mobile-menu__link" href="#" tone="inherit" layout="flex"><ServiceLogo class="crs-mobile-menu__service-logo" :service="item.service" />{{item.label}}</Link></nav></section><slot/></aside></Transition></Teleport></template>
<style scoped>.crs-mobile-menu{position:fixed;z-index:var(--crs-z-mobile-menu);inset:0;box-sizing:border-box;overflow-y:auto;background:var(--crs-white);padding:var(--crs-space-24);color:var(--crs-black-850);font:400 var(--crs-font-16)/var(--crs-leading-22) var(--crs-font-family)}.crs-mobile-menu header,.crs-mobile-menu__group>div{display:flex;align-items:center;justify-content:space-between}.crs-mobile-menu header{margin-bottom:var(--crs-space-24)}.crs-mobile-menu header p,.crs-mobile-menu h2{margin:0;font:600 var(--crs-font-18)/var(--crs-leading-22) var(--crs-font-family)}.crs-mobile-menu__group{display:grid;gap:var(--crs-space-8);padding-block:var(--crs-space-16);border-top:var(--crs-border-1) solid var(--crs-black-100)}.crs-mobile-menu nav{display:grid}.crs-mobile-menu__link{display:flex;min-height:var(--crs-size-40);align-items:center;gap:var(--crs-space-8);color:var(--crs-black-850)}.crs-mobile-menu__link:hover{color:var(--crs-blue-600)}.crs-mobile-menu__service-logo{display:grid;width:var(--crs-size-24);height:var(--crs-size-24);place-items:center;border-radius:var(--crs-radius-6);color:var(--crs-white);font-size:var(--crs-font-12);font-weight:600}.crs-mobile-menu__more{color:var(--crs-blue-500)!important}.crs-menu-enter-active,.crs-menu-leave-active{transition:transform var(--crs-duration-normal) var(--crs-ease)}.crs-menu-enter-from,.crs-menu-leave-to{transform:translateX(100%)}@media(min-width:768px){.crs-mobile-menu{right:auto;width:var(--crs-size-360);box-shadow:var(--crs-shadow-sheet)}}</style>
