<script setup lang="ts">
const open=defineModel<boolean>('open',{default:false});const value=defineModel<string>('value',{default:'popular'});withDefaults(defineProps<{options?:{label:string;value:string}[]}>(),{options:()=>[{label:'По популярности',value:'popular'},{label:'Сначала новые',value:'new'},{label:'По рейтингу',value:'rating'},{label:'Сначала дешевле',value:'price-asc'},{label:'Сначала дороже',value:'price-desc'},{label:'По длительности',value:'duration'}]})
let trigger:HTMLElement|null=null
function choose(next:string){value.value=next;open.value=false;nextTick(()=>trigger?.focus())}
function onKeydown(event:KeyboardEvent){if(event.key==='Escape'){open.value=false;nextTick(()=>trigger?.focus())}}
watch(open,next=>{if(next)trigger=document.activeElement as HTMLElement});onMounted(()=>window.addEventListener('keydown',onKeydown));onBeforeUnmount(()=>window.removeEventListener('keydown',onKeydown))
</script>
<template><Teleport to="body"><div v-if="open" class="crs-sort-sheet" @click.self="open=false"><section role="dialog" aria-modal="true" aria-label="Сортировка"><span class="crs-sort-sheet__handle"/><h2>Сортировка</h2><OptionList v-model="value" class="crs-sort-sheet__options" :items="options" selection-mode="single" embedded label="Сортировка" @select="next => choose(String(next))" @escape="open=false" /></section></div></Teleport></template>
<style scoped>.crs-sort-sheet{position:fixed;z-index:var(--crs-z-modal);inset:0;display:flex;align-items:flex-start;justify-content:center;background:transparent;padding-top:var(--crs-size-94)}.crs-sort-sheet section{box-sizing:border-box;width:var(--crs-size-320);overflow:hidden;border-radius:var(--crs-radius-12);background:var(--crs-white);padding:var(--crs-space-8) 0;box-shadow:var(--crs-shadow-sheet)}.crs-sort-sheet h2,.crs-sort-sheet__handle{display:none}.crs-sort-sheet__options{--crs-option-item-padding-left:var(--crs-space-16);--crs-option-item-padding-right:var(--crs-space-16)}@media(max-width:767px){.crs-sort-sheet{align-items:flex-end;background:var(--crs-overlay);padding-top:var(--crs-space-40)}.crs-sort-sheet section{width:100%;border-radius:var(--crs-radius-24) var(--crs-radius-24) 0 0;padding:var(--crs-space-24) 0;box-shadow:none}.crs-sort-sheet__handle{display:block;width:var(--crs-size-40);height:var(--crs-size-4);border-radius:var(--crs-radius-full);background:var(--crs-black-200);margin:calc(var(--crs-space-16) * -1) auto var(--crs-space-20)}.crs-sort-sheet h2{display:block;margin:0 var(--crs-space-24) var(--crs-space-8);font:600 var(--crs-font-24)/var(--crs-leading-28) var(--crs-font-family)}.crs-sort-sheet__options{--crs-option-item-padding-left:var(--crs-space-24);--crs-option-item-padding-right:var(--crs-space-24)}}</style>
